# Generated by Django 3.0.4 on 2020-09-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='address',
        ),
    ]
